<?php

use Illuminate\Database\Seeder;

class PaisesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()	{
    	$paises = [
  	 		['ID' => 1, 'pais' => 'AFGHANISTAN', 'codigo'  => 'AF',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 2, 'pais' => 'ALAND ISLANDS', 'codigo'  => 'AX',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 3, 'pais' => 'ALBANIA', 'codigo'  => 'AL',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 4, 'pais' => 'ALEMANIA', 'codigo'  => 'DE',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 5, 'pais' => 'ALGERIA', 'codigo'  => 'DZ',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 6, 'pais' => 'AMERICAN SAMOA', 'codigo'  => 'AS',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 7, 'pais' => 'ANDORRA', 'codigo'  => 'AD',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 8, 'pais' => 'ANGOLA', 'codigo'  => 'AO',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 9, 'pais' => 'ANGUILLA', 'codigo'  => 'AI',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 10, 'pais' => 'ANTARCTICA', 'codigo'  => 'AQ',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 11, 'pais' => 'ANTIGUA Y BARBUDA', 'codigo'  => 'AG',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 12, 'pais' => 'ARABIA SAUDITA', 'codigo'  => 'SA',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 13, 'pais' => 'ARGENTINA', 'codigo'  => 'AR',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 14, 'pais' => 'ARMENIA', 'codigo'  => 'AM',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 15, 'pais' => 'ARUBA', 'codigo'  => 'AW',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 16, 'pais' => 'ASIA / REGION PACIFICO', 'codigo'  => 'AP',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 17, 'pais' => 'AUSTRALIA', 'codigo'  => 'AU',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 18, 'pais' => 'AUSTRIA', 'codigo'  => 'AT',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 19, 'pais' => 'AZERBAIJAN', 'codigo'  => 'AZ',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 20, 'pais' => 'BAHAMAS', 'codigo'  => 'BS',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 21, 'pais' => 'BAHRAIN', 'codigo'  => 'BH',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 22, 'pais' => 'BANGLADESH', 'codigo'  => 'BD',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 23, 'pais' => 'BARBADOS', 'codigo'  => 'BB',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 24, 'pais' => 'BELARUS', 'codigo'  => 'BY',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 25, 'pais' => 'BELGICA', 'codigo'  => 'BE',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 26, 'pais' => 'BELICE', 'codigo'  => 'BZ',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 27, 'pais' => 'BENIN', 'codigo'  => 'BJ',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 28, 'pais' => 'BERMUDA', 'codigo'  => 'BM',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 29, 'pais' => 'BHUTAN', 'codigo'  => 'BT',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 30, 'pais' => 'BOLIVIA', 'codigo'  => 'BO',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 31, 'pais' => 'BONAIR', 'codigo'  => 'BQ',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 32, 'pais' => 'BOSNIA AND HERZEGOVINA', 'codigo'  => 'BA',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 33, 'pais' => 'BOTSWANA', 'codigo'  => 'BW',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 34, 'pais' => 'BRASIL', 'codigo'  => 'BR',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 35, 'pais' => 'BRITISH INDIAN OCEAN TERRITORY', 'codigo'  => 'IO',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 36, 'pais' => 'BRUNEI DARUSSALAM', 'codigo'  => 'BN',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 37, 'pais' => 'BULGARIA', 'codigo'  => 'BG',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 38, 'pais' => 'BURKINA FASO', 'codigo'  => 'BF',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 39, 'pais' => 'BURUNDI', 'codigo'  => 'BI',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 40, 'pais' => 'CABO VERDE', 'codigo'  => 'CV',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 41, 'pais' => 'CAMBOYA', 'codigo'  => 'KH',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 42, 'pais' => 'CAMERUN', 'codigo'  => 'CM',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 43, 'pais' => 'CANADA', 'codigo'  => 'CA',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 44, 'pais' => 'CHAD', 'codigo'  => 'TD',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 45, 'pais' => 'CHILE', 'codigo'  => 'CL',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 46, 'pais' => 'CHINA', 'codigo'  => 'CN',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 47, 'pais' => 'CHIPRE', 'codigo'  => 'CY',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 48, 'pais' => 'COCOS (KEELING) ISLANDS', 'codigo'  => 'CC',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 49, 'pais' => 'COLOMBIA', 'codigo'  => 'CO',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 50, 'pais' => 'COMOROS', 'codigo'  => 'KM',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 51, 'pais' => 'CONG', 'codigo'  => 'CD',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 52, 'pais' => 'CONGO', 'codigo'  => 'CG',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 53, 'pais' => 'COOK ISLANDS', 'codigo'  => 'CK',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 54, 'pais' => 'COSTA RICA', 'codigo'  => 'CR',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 55, 'pais' => "COTE D'IVOIRE", 'codigo'  => 'CI',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 56, 'pais' => 'CROACIA', 'codigo'  => 'HR',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 57, 'pais' => 'CUBA', 'codigo'  => 'CU',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 58, 'pais' => 'CURACAO', 'codigo'  => 'CW',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 59, 'pais' => 'DINAMARCA', 'codigo'  => 'DK',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 60, 'pais' => 'DJIBOUTI', 'codigo'  => 'DJ',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 61, 'pais' => 'DOMINICA', 'codigo'  => 'DM',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 62, 'pais' => 'ECUADOR', 'codigo'  => 'EC',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 63, 'pais' => 'EGIPTO', 'codigo'  => 'EG',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 64, 'pais' => 'EL SALVADOR', 'codigo'  => 'SV',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 65, 'pais' => 'EMIRATOS ARABES UNIDOS', 'codigo'  => 'AE',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 66, 'pais' => 'ERITREA', 'codigo'  => 'ER',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 67, 'pais' => 'ESLOVAQUIA', 'codigo'  => 'SK',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 68, 'pais' => 'ESLOVENIA', 'codigo'  => 'SI',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 69, 'pais' => 'ESPAÑA', 'codigo'  => 'ES',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 70, 'pais' => 'ESTADOS UNIDOS', 'codigo'  => 'US',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 71, 'pais' => 'ESTONIA', 'codigo'  => 'EE',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 72, 'pais' => 'ETIOPIA', 'codigo'  => 'ET',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 73, 'pais' => 'FAROE ISLANDS', 'codigo'  => 'FO',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 74, 'pais' => 'FIJI', 'codigo'  => 'FJ',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 75, 'pais' => 'FILIPINAS', 'codigo'  => 'PH',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 76, 'pais' => 'FINLANDIA', 'codigo'  => 'FI',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 77, 'pais' => 'FRANCIA', 'codigo'  => 'FR',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 78, 'pais' => 'FRENCH POLYNESIA', 'codigo'  => 'PF',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 79, 'pais' => 'GABON', 'codigo'  => 'GA',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 80, 'pais' => 'GAMBIA', 'codigo'  => 'GM',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 81, 'pais' => 'GANA', 'codigo'  => 'GH',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 82, 'pais' => 'GEORGIA', 'codigo'  => 'GE',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 83, 'pais' => 'GIBRALTAR', 'codigo'  => 'GI',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 84, 'pais' => 'GRANADA', 'codigo'  => 'GD',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 85, 'pais' => 'GRECIA', 'codigo'  => 'GR',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 86, 'pais' => 'GROENLANDIA', 'codigo'  => 'GL',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 87, 'pais' => 'GUADELOUPE', 'codigo'  => 'GP',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 88, 'pais' => 'GUAM', 'codigo'  => 'GU',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 89, 'pais' => 'GUATEMALA', 'codigo'  => 'GT',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 90, 'pais' => 'GUERNSEY', 'codigo'  => 'GG',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 91, 'pais' => 'GUINEA', 'codigo'  => 'GN',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 92, 'pais' => 'GUINEA ECUATORIAL', 'codigo'  => 'GQ',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 93, 'pais' => 'GUINEA-BISSAU', 'codigo'  => 'GW',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 94, 'pais' => 'GUYANA', 'codigo'  => 'GY',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 95, 'pais' => 'GUYANA FRANCESA', 'codigo'  => 'GF',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 96, 'pais' => 'HAITI', 'codigo'  => 'HT',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 97, 'pais' => 'HOLANDA, PAISES BAJOS', 'codigo'  => 'NL',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 98, 'pais' => 'HOLY SEE (VATICAN CITY STATE)', 'codigo'  => 'VA',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 99, 'pais' => 'HONDURAS', 'codigo'  => 'HN',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 100, 'pais' => 'HUNGRIA', 'codigo'  => 'HU',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 101, 'pais' => 'INDIA', 'codigo'  => 'IN',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 102, 'pais' => 'INDONESIA', 'codigo'  => 'ID',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 103, 'pais' => 'IRA', 'codigo'  => 'IR',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 104, 'pais' => 'IRAQ', 'codigo'  => 'IQ',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 105, 'pais' => 'IRLANDA', 'codigo'  => 'IE',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 106, 'pais' => 'ISLANDIA', 'codigo'  => 'IS',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 107, 'pais' => 'ISLAS (MALVINAS)', 'codigo'  => 'FK',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 108, 'pais' => 'ISLAS CAIMAN', 'codigo'  => 'KY',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 109, 'pais' => 'ISLAS DE PASCUA', 'codigo'  => 'CX',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 110, 'pais' => 'ISLAS SALOMON', 'codigo'  => 'SB',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 111, 'pais' => 'ISLE OF MAN', 'codigo'  => 'IM',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 112, 'pais' => 'ISRAEL', 'codigo'  => 'IL',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 113, 'pais' => 'ITALIA', 'codigo'  => 'IT',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 114, 'pais' => 'JAMAICA', 'codigo'  => 'JM',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 115, 'pais' => 'JAPAN', 'codigo'  => 'JP',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 116, 'pais' => 'JERSEY', 'codigo'  => 'JE',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 117, 'pais' => 'JORDAN', 'codigo'  => 'JO',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 118, 'pais' => 'KAZAKHSTAN', 'codigo'  => 'KZ',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 119, 'pais' => 'KENYA', 'codigo'  => 'KE',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 120, 'pais' => 'KIRIBATI', 'codigo'  => 'KI',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 121, 'pais' => 'KORE', 'codigo'  => 'KR',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 122, 'pais' => 'KUWAIT', 'codigo'  => 'KW',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 123, 'pais' => 'KYRGYZSTAN', 'codigo'  => 'KG',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 124, 'pais' => "LAO PEOPLE'S DEMOCRATIC REPUBLIC", 'codigo'  => 'LA',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 125, 'pais' => 'LATVIA', 'codigo'  => 'LV',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 126, 'pais' => 'LEBANON', 'codigo'  => 'LB',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 127, 'pais' => 'LESOTHO', 'codigo'  => 'LS',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 128, 'pais' => 'LIBERIA', 'codigo'  => 'LR',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 129, 'pais' => 'LIBYA', 'codigo'  => 'LY',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 130, 'pais' => 'LIECHTENSTEIN', 'codigo'  => 'LI',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 131, 'pais' => 'LITHUANIA', 'codigo'  => 'LT',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 132, 'pais' => 'LUXEMBOURG', 'codigo'  => 'LU',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 133, 'pais' => 'MACAU', 'codigo'  => 'MO',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 134, 'pais' => 'MACEDONIA', 'codigo'  => 'MK',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 135, 'pais' => 'MADAGASCAR', 'codigo'  => 'MG',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 136, 'pais' => 'MALASIA', 'codigo'  => 'MY',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 137, 'pais' => 'MALAWI', 'codigo'  => 'MW',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 138, 'pais' => 'MALDIVES', 'codigo'  => 'MV',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 139, 'pais' => 'MALI', 'codigo'  => 'ML',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 140, 'pais' => 'MALTA', 'codigo'  => 'MT',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 141, 'pais' => 'MARRUECOS', 'codigo'  => 'MA',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 142, 'pais' => 'MARSHALL ISLANDS', 'codigo'  => 'MH',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 143, 'pais' => 'MARTINIQUE', 'codigo'  => 'MQ',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 144, 'pais' => 'MAURITANIA', 'codigo'  => 'MR',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 145, 'pais' => 'MAURITIUS', 'codigo'  => 'MU',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 146, 'pais' => 'MAYOTTE', 'codigo'  => 'YT',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 147, 'pais' => 'MEXICO', 'codigo'  => 'MX',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 148, 'pais' => 'MICRONESI', 'codigo'  => 'FM',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 149, 'pais' => 'MOLDOV', 'codigo'  => 'MD',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 150, 'pais' => 'MONACO', 'codigo'  => 'MC',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 151, 'pais' => 'MONGOLIA', 'codigo'  => 'MN',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 152, 'pais' => 'MONTENEGRO', 'codigo'  => 'ME',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 153, 'pais' => 'MONTSERRAT', 'codigo'  => 'MS',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 154, 'pais' => 'MOZAMBIQUE', 'codigo'  => 'MZ',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 155, 'pais' => 'MYANMAR', 'codigo'  => 'MM',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 156, 'pais' => 'NAMIBIA', 'codigo'  => 'NA',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 157, 'pais' => 'NAURU', 'codigo'  => 'NR',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 158, 'pais' => 'NEPAL', 'codigo'  => 'NP',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 159, 'pais' => 'NICARAGUA', 'codigo'  => 'NI',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 160, 'pais' => 'NIGER', 'codigo'  => 'NE',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 161, 'pais' => 'NIGERIA', 'codigo'  => 'NG',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 162, 'pais' => 'NIUE', 'codigo'  => 'NU',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 163, 'pais' => 'NORFOLK ISLAND', 'codigo'  => 'NF',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 164, 'pais' => 'NORTHERN MARIANA ISLANDS', 'codigo'  => 'MP',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 165, 'pais' => 'NORUEGA', 'codigo'  => 'NO',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 166, 'pais' => 'NUEVA CALEDONIA', 'codigo'  => 'NC',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 167, 'pais' => 'NUEVA ZELANDIA', 'codigo'  => 'NZ',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 168, 'pais' => 'OMAN', 'codigo'  => 'OM',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 169, 'pais' => 'PAKISTAN', 'codigo'  => 'PK',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 170, 'pais' => 'PALAU', 'codigo'  => 'PW',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 171, 'pais' => 'PALESTINA', 'codigo'  => 'PS',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 172, 'pais' => 'PANAMA', 'codigo'  => 'PA',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 173, 'pais' => 'PAPUA NEW GUINEA', 'codigo'  => 'PG',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 174, 'pais' => 'PARAGUAY', 'codigo'  => 'PY',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 175, 'pais' => 'PERU', 'codigo'  => 'PE',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 176, 'pais' => 'PITCAIRN ISLANDS', 'codigo'  => 'PN',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 177, 'pais' => 'POLONIA', 'codigo'  => 'PL',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 178, 'pais' => 'PORTUGAL', 'codigo'  => 'PT',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 179, 'pais' => 'PUERTO RICO', 'codigo'  => 'PR',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 180, 'pais' => 'QATAR', 'codigo'  => 'QA',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 181, 'pais' => 'REINO UNIDO', 'codigo'  => 'GB',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 182, 'pais' => 'REPUBLICA CENTRAL DE AFRICA', 'codigo'  => 'CF',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 183, 'pais' => 'REPUBLICA CHECA', 'codigo'  => 'CZ',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 184, 'pais' => 'REPUBLICA DOMINICANA', 'codigo'  => 'DO',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 185, 'pais' => 'REUNION', 'codigo'  => 'RE',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 186, 'pais' => 'ROMANIA', 'codigo'  => 'RO',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 187, 'pais' => 'RUANDA', 'codigo'  => 'RW',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 188, 'pais' => 'RUSIA', 'codigo'  => 'RU',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 189, 'pais' => 'SAINT BARTHELEMY', 'codigo'  => 'BL',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 190, 'pais' => 'SAINT HELENA', 'codigo'  => 'SH',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 191, 'pais' => 'SAINT KITTS AND NEVIS', 'codigo'  => 'KN',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 192, 'pais' => 'SAINT PIERRE AND MIQUELON', 'codigo'  => 'PM',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 193, 'pais' => 'SAINT VINCENT AND THE GRENADINES', 'codigo'  => 'VC',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 194, 'pais' => 'SAMOA', 'codigo'  => 'WS',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 195, 'pais' => 'SAN MARINO', 'codigo'  => 'SM',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 196, 'pais' => 'SAN MARTIN', 'codigo'  => 'MF',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 197, 'pais' => 'SANTA LUCIA', 'codigo'  => 'LC',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 198, 'pais' => 'SAO TOME AND PRINCIPE', 'codigo'  => 'ST',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 199, 'pais' => 'SENEGAL', 'codigo'  => 'SN',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 200, 'pais' => 'SERBIA', 'codigo'  => 'RS',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 201, 'pais' => 'SEYCHELLES', 'codigo'  => 'SC',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 202, 'pais' => 'SIERRA LEONE', 'codigo'  => 'SL',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 203, 'pais' => 'SINGAPUR', 'codigo'  => 'SG',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 204, 'pais' => 'SINT MAARTEN (DUTCH PART)', 'codigo'  => 'SX',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 205, 'pais' => 'SIRIA REPUBLICA ARABE', 'codigo'  => 'SY',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 206, 'pais' => 'SOMALIA', 'codigo'  => 'SO',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 207, 'pais' => 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', 'codigo'  => 'GS',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 208, 'pais' => 'SRI LANKA', 'codigo'  => 'LK',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 209, 'pais' => 'SUDAFRICA', 'codigo'  => 'ZA',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 210, 'pais' => 'SUDAN', 'codigo'  => 'SD',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 211, 'pais' => 'SUDAN DEL SUR', 'codigo'  => 'SS',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 212, 'pais' => 'SUECIA', 'codigo'  => 'SE',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 213, 'pais' => 'SUIZA', 'codigo'  => 'CH',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 214, 'pais' => 'SURINAM', 'codigo'  => 'SR',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 215, 'pais' => 'SVALBARD AND JAN MAYEN', 'codigo'  => 'SJ',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 216, 'pais' => 'SWAZILAND', 'codigo'  => 'SZ',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 217, 'pais' => 'TAILANDIA', 'codigo'  => 'TH',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 218, 'pais' => 'TAIWAN', 'codigo'  => 'TW',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 219, 'pais' => 'TAJIKISTAN', 'codigo'  => 'TJ',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 220, 'pais' => 'TANZANIA', 'codigo'  => 'TZ',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 221, 'pais' => 'TIMOR-LESTE', 'codigo'  => 'TL',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 222, 'pais' => 'TOGO', 'codigo'  => 'TG',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 223, 'pais' => 'TOKELAU', 'codigo'  => 'TK',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 224, 'pais' => 'TONGA', 'codigo'  => 'TO',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 225, 'pais' => 'TRINIDAD Y TOBAGO', 'codigo'  => 'TT',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 226, 'pais' => 'TUNISIA', 'codigo'  => 'TN',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 227, 'pais' => 'TURKMENISTAN', 'codigo'  => 'TM',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 228, 'pais' => 'TURKS AND CAICOS ISLANDS', 'codigo'  => 'TC',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 229, 'pais' => 'TURQUIA', 'codigo'  => 'TR',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 230, 'pais' => 'TUVALU', 'codigo'  => 'TV',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 231, 'pais' => 'UCRANIA', 'codigo'  => 'UA',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 232, 'pais' => 'UGANDA', 'codigo'  => 'UG',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 233, 'pais' => 'UNITED STATES MINOR OUTLYING ISLANDS', 'codigo'  => 'UM',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 234, 'pais' => 'URUGUAY', 'codigo'  => 'UY',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 235, 'pais' => 'UZBEKISTAN', 'codigo'  => 'UZ',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 236, 'pais' => 'VANUATU', 'codigo'  => 'VU',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 237, 'pais' => 'VENEZUELA', 'codigo'  => 'VE',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 238, 'pais' => 'VIETNAM', 'codigo'  => 'VN',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 239, 'pais' => 'VIRGIN ISLAND', 'codigo'  => 'VG',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 240, 'pais' => 'WALLIS AND FUTUNA', 'codigo'  => 'WF',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 241, 'pais' => 'WESTERN SAHARA', 'codigo'  => 'EH',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 242, 'pais' => 'YEMEN', 'codigo'  => 'YE',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 243, 'pais' => 'ZAMBIA', 'codigo'  => 'ZM',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))],
				['ID' => 244, 'pais' => 'ZIMBABWE', 'codigo'  => 'ZW',	'fecha_de_creacion'	=>	date(	'Y-m-d H:i:s',  strtotime('now'))]
    	];

    	DB::table('paises')->insert(	$paises);
    }
}
